/*
 * arduino_inference.h — AUTO-GENERATED by src/train_tinyml.py
 * DO NOT EDIT MANUALLY. Re-run train_tinyml.py to regenerate.
 *
 * In plain English: this file contains the trained machine-learning model
 * baked directly into C++ constants. When you #include this file in the
 * Arduino sketch, the model weights are compiled into flash memory (not SRAM)
 * so they don't eat into the 2 KB working memory budget.
 *
 * How to use this file:
 *   1. Include it in your .ino:  #include "arduino_inference.h"
 *   2. Scale your 5 band features using BAND_SCALER_MEAN and BAND_SCALER_SCALE
 *   3. Call score(scaled_input, output) to get 3 decision values
 *   4. Take argmax of output[0..2] to get the predicted class index
 *   5. Look up the class name in PRED_CLASSES[prediction_id]
 *
 * Model   : SGDClassifier(loss=log_loss, penalty=l1)
 * Features: 5 EEG band-power scalars (Delta, Theta, Alpha, Beta, Gamma)
 * Classes : calm (0), relaxed (1), stressed (2)
 * Accuracy: 74.0% on 20% held-out test set
 *
 * AVR NOTE: On ATmega328P, sizeof(double) == sizeof(float) == 4 bytes.
 *   score() uses double types; AVR-GCC compiles them as 4-byte floats.
 *   The model weight literals in score() are placed in FLASH by AVR-GCC,
 *   NOT in SRAM — so they cost 0 bytes of your 2 KB working memory budget.
 *
 * C++ NOTE: score() is written without C99 compound literals so it
 *   compiles cleanly under C++11 (used by the Arduino IDE for .ino files).
 *
 * Validation vector: raw_input=[0.5,0.5,0.5,0.5,0.5]
 *   Expected prediction_id : 2  (stressed)
 *   Expected confidence    : 1.0000
 *   (Note: 0.5 raw input is an extreme outlier above the training
 *    distribution — scaler maps it to large positive values.
 *    This is correct behaviour; verify with realistic EEG inputs.)
 */

#pragma once
#include <avr/pgmspace.h>

/*
 * StandardScaler parameters stored in FLASH (PROGMEM).
 *
 * WHY PROGMEM? These arrays would normally go in SRAM, but the Arduino Uno
 * has only 2 KB of SRAM and we need most of it for the FFT buffers.
 * The PROGMEM attribute tells AVR-GCC to put the arrays in flash instead.
 * To read them back, use pgm_read_float_near() — see mindtune_edge.ino.
 *
 * Order: [Delta, Theta, Alpha, Beta, Gamma]
 * Formula: scaled[i] = (raw_band_power[i] - MEAN[i]) / SCALE[i]
 */
static const float BAND_SCALER_MEAN[5]  PROGMEM = { 0.09183148f, 0.04502182f, 0.02965970f, 0.01678868f, 0.01046119f };
static const float BAND_SCALER_SCALE[5] PROGMEM = { 0.04006524f, 0.02089566f, 0.01705777f, 0.00745868f, 0.00419869f };

/* Class label lookup: PRED_CLASSES[prediction_id] → human-readable name.
 * Index 0=calm, 1=relaxed, 2=stressed (matches Python CLASSES list). */
static const char* const PRED_CLASSES[3] = { "calm", "relaxed", "stressed" };

/*
 * score(): One-vs-Rest (OvR) linear decision function.
 *
 * This is the classifier itself — a direct translation of the Python model's
 * coef_ and intercept_ arrays into arithmetic. Each output[i] is a dot product:
 *   output[i] = intercept[i] + weight[i,0]*input[0] + ... + weight[i,4]*input[4]
 *
 * The class with the highest output value is the predicted class (argmax).
 * L1 penalty (penalty='l1') in training forces some weights to exactly zero,
 * which is why some input[k] terms are absent — those features don't contribute
 * to that class's decision and were pruned to save compute.
 *
 * Args:
 *   input  — pointer to 5 z-scored band-power features (after applying scaler)
 *   output — pointer to 3 doubles (one decision value per class)
 */
void score(double* input, double* output) {
    output[0] = -0.8665357790940681 + input[0] * -0.3086582691282320 + input[1] * -0.9204997154762579 + input[2] * 3.1180629958968189 + input[3] * 0.5534958380362084 + input[4] * -1.1155842068085007;
    output[1] = -1.0337644461390918 + input[0] * 0.2494096568419120 + input[1] * 1.0212753392293494 + input[2] * -1.2946316845847550 + input[3] * 0.8194574241428491 + input[4] * -0.5320899552614659;
    output[2] = -2.5309764820771616 + input[0] * -0.5980654187316252 + input[2] * -4.0759279986071490 + input[3] * -2.4170512937524560 + input[4] * 2.4027266702976320;
}
