/*
 * mindtune_edge.ino — MindTune-OS Edge Inference Sketch
 *
 * In plain English: this sketch turns an Arduino Uno into a real-time EEG
 * stress detector. It samples the analog EEG signal 256 times per second,
 * converts 128 consecutive samples into frequency content using a Fast Fourier
 * Transform (FFT), sums that frequency content into 5 brainwave bands, runs
 * those 5 numbers through the trained classifier, and transmits the result
 * over Serial — one classification every 0.5 seconds.
 *
 * Hardware : BioAmp EXG Pill (1-channel EEG) on Analog Pin A0
 *            Arduino Uno R3 (ATmega328P, 16 MHz, 2KB SRAM)
 *
 * Pipeline
 * ────────
 *  1. Timer1 ISR samples A0 at 256 Hz → circular buffer raw[128]
 *  2. Once 128 samples are ready, copy to vReal[], restart ISR buffer
 *  3. Apply 128-point Hanning-windowed FFT via arduinoFFT
 *  4. Sum FFT magnitudes into 5 EEG bands (Delta–Gamma)
 *  5. Apply StandardScaler (params from PROGMEM via arduino_inference.h)
 *  6. Call score() from arduino_inference.h → 3 OvR decision values
 *  7. Softmax → prediction_id + confidence
 *  8. Transmit: "PRED_ID,CONFIDENCE\n"  e.g. "2,0.87\n"
 *
 * SRAM Budget (ATmega328P — 2048 bytes total)
 * ────────────────────────────────────────────
 *   vReal[128]  double : 512 bytes  (double==float==4B on AVR)
 *   vImag[128]  double : 512 bytes  (double==float==4B on AVR)
 *   raw[128]    int    : 256 bytes  (volatile, ISR circular buffer)
 *   Serial TX/RX bufs  :  64 bytes  (Arduino default)
 *   AVR runtime + stack: ~150 bytes
 *   Local vars/overhead:  ~50 bytes
 *   ────────────────────────────────
 *   Total estimate      : ~1544 bytes  (< 1600 byte target ✓)
 *
 * Model weights (in score() body) and scaler params (PROGMEM) are stored
 * in flash — they do NOT consume SRAM.
 *
 * Serial Packet Format
 * ────────────────────
 *  Normal    : "ID,CONF\n"        e.g. "2,0.87\n"
 *  Debug mode: additional "DBG:band=val ..." line before prediction
 *
 * Inference rate : one classification per 128-sample window = 0.5 s
 *
 * Required Library
 * ────────────────
 *  arduinoFFT v1.9.x — install via: Sketch > Include Library > Manage Libraries
 *  (If using v2.x, see comments marked [FFT_V2] below for API differences.)
 *
 * Band–Bin Alignment (128-pt FFT @ 256 Hz → 2 Hz/bin)
 * ────────────────────────────────────────────────────
 *   Band    Hz range   Bins   Frequencies captured
 *   Delta   1–3 Hz     1      bin 1 → 2 Hz
 *   Theta   4–8 Hz     2–4    4, 6, 8 Hz
 *   Alpha   9–13 Hz    5–6    10, 12 Hz
 *   Beta    14–30 Hz   7–15   14, 16, …, 30 Hz
 *   Gamma   31–45 Hz   16–22  32, 34, …, 44 Hz
 *
 * Matches training aggregation in src/train_tinyml.py: mean of Kaggle CSV
 * freq_ columns within each band's Hz range (proxy-trained, scaler-aligned).
 */

#include <avr/pgmspace.h>
#include <math.h>
#include "arduinoFFT.h"        // install via Library Manager
#include "arduino_inference.h" // auto-generated by src/train_tinyml.py

/* ── Compile-time configuration ──────────────────────────────────────────── */

// Set to 1 to print band power values to Serial each cycle (for calibration).
// Useful for checking that real EEG signals are reaching the ADC correctly.
// Set to 0 for production — avoids adding Serial print overhead.
#define DEBUG_BANDS 0

/* ── Constants ───────────────────────────────────────────────────────────── */

static const uint8_t  SAMPLES     = 128;   // FFT window size (samples per classification)
static const uint16_t SAMPLE_RATE = 256;   // Hz — must match Timer1 setup below
static const uint8_t  N_BANDS     = 5;     // Delta, Theta, Alpha, Beta, Gamma
static const uint8_t  N_CLASSES   = 3;     // calm, relaxed, stressed

// FFT frequency resolution = SAMPLE_RATE / SAMPLES = 256/128 = 2 Hz per bin.
// Bin k covers the frequency range: k×2 Hz to (k+1)×2 Hz.
// Bin 0 = DC (0 Hz) — always excluded from EEG analysis.
// These bin ranges match the band definitions in src/train_tinyml.py exactly.
static const uint8_t BAND_BIN_LO[N_BANDS] = {  1,  2,  5,  7, 16 };  // first bin for each band
static const uint8_t BAND_BIN_HI[N_BANDS] = {  1,  4,  6, 15, 22 };  // last bin for each band
// Pre-computed bin count per band (hi - lo + 1): {1, 3, 2, 9, 7}
// Used to compute the mean magnitude rather than sum, matching Python mean().
static const uint8_t BAND_BIN_N[N_BANDS]  = {  1,  3,  2,  9,  7 };

/* ── SRAM-resident working arrays ────────────────────────────────────────── */

// arduinoFFT v1.9.x API takes double* — declare as double to avoid type mismatch.
// On ATmega328P, sizeof(double)==sizeof(float)==4 bytes, so no extra SRAM is used.
static double vReal[SAMPLES];  // FFT real input / magnitude output (512 bytes)
static double vImag[SAMPLES];  // FFT imaginary input (zeroed each window)  (512 bytes)

// ISR circular buffer — written by Timer1 ISR, read by main loop.
// 'volatile' is REQUIRED here: without it, the compiler may cache these variables
// in CPU registers and never see updates written by the ISR.
static volatile int     raw[SAMPLES];  // 10-bit ADC values from A0   (256 bytes)
static volatile uint8_t bufIdx  = 0;   // next write position in raw[]
static volatile bool    bufFull = false;  // true once raw[] has 128 new samples

/* ── arduinoFFT instance ─────────────────────────────────────────────────── */
// The arduinoFFT library does the heavy maths of converting 128 time-domain
// samples into 64 frequency bins (complex FFT → magnitude spectrum).
// [FFT_V2] If you have arduinoFFT v2.x: use ArduinoFFT<float> FFT; instead.
arduinoFFT FFT = arduinoFFT();

/* ── Timer1 setup: 256 Hz CTC interrupt ─────────────────────────────────── */
//
// WHY Timer1? We need a hardware timer to trigger ADC sampling at a precise
// fixed rate. The Arduino loop() speed varies depending on how much work
// each iteration does, so we can't use delay() for accurate sampling.
// Timer1 fires an Interrupt Service Routine (ISR) at exactly 256 Hz regardless.
//
// How the frequency is calculated:
//   Target frequency : 256 Hz
//   Prescaler        : 64  → F_timer = 16,000,000 / 64 = 250,000 Hz
//   OCR1A (compare)  : 975 → F_ISR   = 250,000 / (975 + 1) = 256.15 Hz (< 0.1% error)
//
// CTC mode (Clear Timer on Compare match): counter resets to 0 when it hits OCR1A.
// CS1[2:0] = 0b011 → prescaler 64 (CS12=0, CS11=1, CS10=1)

void setupTimer1() {
    TCCR1A = 0;                           // clear Timer1 control register A
    TCCR1B = 0;                           // clear Timer1 control register B
    TCNT1  = 0;                           // reset counter to 0

    OCR1A = 975;                          // fire ISR when counter reaches 975
    TCCR1B |= (1 << WGM12);              // CTC mode: reset counter on compare match
    TCCR1B |= (1 << CS11) | (1 << CS10); // prescaler = 64
    TIMSK1 |= (1 << OCIE1A);             // enable the compare-match-A interrupt
}

/* ── Timer1 ISR: sample A0 into circular buffer ──────────────────────────── */
//
// ISR = Interrupt Service Routine. This function is called automatically by
// the hardware 256 times per second, interrupting whatever loop() is doing.
//
// What it does: reads one 10-bit ADC value from pin A0 (range 0–1023) and
// stores it in raw[bufIdx]. After 128 samples, it raises the bufFull flag
// and stops until the main loop consumes the buffer.
//
// Why we stop after 128 samples: the main loop needs a stable snapshot to run
// the FFT on. If the ISR kept overwriting raw[] while the FFT was computing,
// the results would be corrupted. Once bufFull=true, the ISR simply does
// nothing (the `if (!bufFull)` guard) until the main loop resets the index.
//
// Timing: fires every ~3.9 ms. analogRead() takes ~112 µs at 16 MHz,
// leaving 3794 µs of headroom — well within the 3906 µs ISR period.

ISR(TIMER1_COMPA_vect) {
    if (!bufFull) {
        raw[bufIdx] = analogRead(A0);  // read EEG voltage as 10-bit integer (0–1023)
        bufIdx++;
        if (bufIdx >= SAMPLES) {
            bufFull = true;            // signal main loop: 128 fresh samples are ready
            // bufIdx deliberately stays at SAMPLES; main loop resets it after copying
        }
    }
}

/* ── Softmax helper ──────────────────────────────────────────────────────── */
//
// score() (from arduino_inference.h) returns 3 raw "decision values" — one per
// class. These are not probabilities; they can be any real number. Softmax
// converts them to probabilities that sum to 1.0 so we can report confidence.
//
// The max-subtraction trick (subtract the largest value before calling exp())
// prevents floating-point overflow — on AVR, exp() of a large positive number
// can produce infinity. Subtracting the max makes all inputs ≤ 0 before exp().
//
// Returns only the probability of the winning class (the confidence score).

static float softmax_confidence(double* scores, int winner) {
    double maxS = scores[0];
    if (scores[1] > maxS) maxS = scores[1];
    if (scores[2] > maxS) maxS = scores[2];

    double expSum = 0.0;
    double expS[N_CLASSES];
    for (uint8_t i = 0; i < N_CLASSES; i++) {
        expS[i]  = exp(scores[i] - maxS);
        expSum  += expS[i];
    }
    return (float)(expS[winner] / expSum);
}

/* ── Setup ───────────────────────────────────────────────────────────────── */

void setup() {
    Serial.begin(115200);
    Serial.println(F("MindTune-OS Edge BCI v1.0"));
    Serial.println(F("Format: PRED_ID,CONFIDENCE"));
    Serial.println(F("Classes: 0=calm  1=relaxed  2=stressed"));
    Serial.println(F("---"));

    setupTimer1();
    sei();  // enable global interrupts
}

/* ── Main loop ───────────────────────────────────────────────────────────── */

void loop() {
    if (!bufFull) return;   // wait for a full 128-sample window

    /* ── Step 1: Snapshot raw buffer, restart ISR collection ─────────────── */
    // Disable ISR briefly (~512 µs for 128 int-to-float copies at 16 MHz)
    // so raw[] is not written while we read it. The ISR will resume immediately
    // after interrupts() and begin filling raw[] from index 0 for the next window.
    noInterrupts();
    for (uint8_t i = 0; i < SAMPLES; i++) {
        vReal[i] = (double)raw[i];
        vImag[i] = 0.0;
    }
    bufIdx  = 0;
    bufFull = false;
    interrupts();

    /* ── Step 2: 128-point Hanning-windowed FFT ───────────────────────────── */
    // [FFT_V2] v2.x: FFT.windowing(FFT_WIN_TYP_HANN, FFT_FORWARD);
    FFT.Windowing(vReal, SAMPLES, FFT_WIN_TYP_HANN, FFT_FORWARD);
    FFT.Compute(vReal, vImag, SAMPLES, FFT_FORWARD);
    // ComplexToMagnitude overwrites vReal with |magnitude|; vImag becomes 0.
    // [FFT_V2] v2.x: FFT.complexToMagnitude();
    FFT.ComplexToMagnitude(vReal, vImag, SAMPLES);

    /* ── Step 3: Sum magnitudes into 5 EEG bands, compute mean per band ───── */
    // Mean aggregation matches the training script (Python mean of freq_ cols).
    // Bin 0 = DC component — excluded from all bands.
    double band_power[N_BANDS];
    for (uint8_t b = 0; b < N_BANDS; b++) {
        double sum = 0.0;
        for (uint8_t k = BAND_BIN_LO[b]; k <= BAND_BIN_HI[b]; k++) {
            sum += vReal[k];
        }
        band_power[b] = sum / (double)BAND_BIN_N[b];
    }

#if DEBUG_BANDS
    Serial.print(F("DBG:"));
    const char* bnames[] = {"D","Th","Al","Be","G"};
    for (uint8_t b = 0; b < N_BANDS; b++) {
        Serial.print(bnames[b]);
        Serial.print('=');
        Serial.print(band_power[b], 4);
        if (b < N_BANDS - 1) Serial.print(' ');
    }
    Serial.println();
#endif

    /* ── Step 4: Apply StandardScaler (params read from PROGMEM) ────────────  */
    // PROGMEM = Program Memory. On AVR, constants marked PROGMEM are stored in
    // flash (32 KB) rather than SRAM (2 KB). They cannot be read with a normal
    // pointer dereference — you must use the pgm_read_*_near() helper macros.
    // The scaler parameters (mean and scale for each band) were computed by
    // Python's StandardScaler.fit() and embedded into arduino_inference.h.
    // Formula: scaled[i] = (raw_value[i] - mean[i]) / scale[i]
    // Scaled input is cast to double to match score()'s expected input type.
    double scaled[N_BANDS];
    for (uint8_t i = 0; i < N_BANDS; i++) {
        float mean_i  = pgm_read_float_near(&BAND_SCALER_MEAN[i]);
        float scale_i = pgm_read_float_near(&BAND_SCALER_SCALE[i]);
        scaled[i] = (band_power[i] - (double)mean_i) / (double)scale_i;
    }

    /* ── Step 5: Classifier inference ─────────────────────────────────────── */
    double scores[N_CLASSES];
    score(scaled, scores);

    // Argmax → prediction_id
    uint8_t pred_id = 0;
    for (uint8_t i = 1; i < N_CLASSES; i++) {
        if (scores[i] > scores[pred_id]) pred_id = i;
    }

    // Softmax → calibrated confidence for the winning class
    float confidence = softmax_confidence(scores, pred_id);

    /* ── Step 6: Transmit compact serial packet ────────────────────────────── */
    // Format: "PRED_ID,CONFIDENCE\n"  e.g. "2,0.87\n"
    // The Python main_loop (or a host bridge script) parses this.
    Serial.print(pred_id);
    Serial.print(',');
    Serial.println(confidence, 2);
}
